# Generated by Django 4.2.7 on 2023-11-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
