###
@port = 8000
@api = http://localhost:{{port}}

### CREATE
POST {{api}}/create/
Content-Type: application/json

{
    "user": "tiber",
    "name": "da8ah",
    "email": "tiber@email.com",
    "mobile": "+593000000001",
}

### READ
GET {{api}}/read/

### USER_ID
@user_id = 1

### UPDATE
PUT {{api}}/update/{{user_id}}
Content-Type: application/json

{
    "user": "tiber",
    "name": "Danilo Ochoa Hidalgo"    
}

### DELETE
DELETE {{api}}/delete/{{user_id}}